config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'restaurants/index'

  get 'restaurants/show'

  get 'restaurants/new'

  get 'restaurants/edit'

  get 'restaurants/:id', to: "restaurants#show"

  get 'restaurants/:restaurant_id/reviews', to: "reviews#index"

  get 'restaurants/:restaurant_id/reviews/new', to: "reviews#new"

  post 'restaurants/:restaurant_id/reviews', to: "reviews#create"

  get 'reviews/:id', to: "reviews#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create, :show ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  RATING = [0, 1, 2, 3, 4, 5]

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5]

  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: RATING }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :review_list, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create(restaurant_params)
    redirect_to restaurants_path(@restaurant)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_path, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.required(:restaurant).permit(:name, :address, :phone_number, :category, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save!
    redirect_to restaurants_path
  end

  def show
    @review = Review.find(params[:id])
  end

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = Review.where(restaurant_id: @restaurant.id)
  end

  private

  def review_params
    params.required(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelp Clone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container text-center form-stuff">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name, input_html: { placeholder: "Waffle House" } %>
    <%= f.input :address, input_html: { placeholder: "123 Waffle St" } %>
    <%= f.input :phone_number, input_html: { placeholder: "205-555-1234" } %>
    <%= f.input :rating, as: :select, collection: Restaurant::RATING, include_blank: "Select a rating" %>
    <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES, include_blank:  "Select a category" %>
    <%= f.submit class: "btn btn-restaurant btn-pink" %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit a Restaurant</h1>
<%= render "form" %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<p><%= link_to "Add Restaurant", new_restaurant_path, class: "btn btn-pink" %></p>
<div class="container text-center restaurants">
<% @restaurants.each do |restaurant| %>
<div class="row card">
  <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
  <p><%= restaurant.address %> |&nbsp;<%= restaurant.phone_number %></p>
  <p><%= restaurant.category %> |&nbsp;<%= restaurant.rating %></p>
</div>
<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Add a New Restaurant</h1>
<br>
<%= render "form" %>

app/views/restaurants/show.html.erb
<div class="container text-center restaurants">
  <div class="row card">
    <h2><%= @restaurant.name %></h2>
    <p><%= @restaurant.address %> |&nbsp;<%= @restaurant.phone_number %></p>
    <p><%= @restaurant.category %> |&nbsp;<%= @restaurant.rating %></p>
  <ul class="list-inline">
    <li><%= link_to "See Reviews", restaurant_reviews_path(@restaurant.id), class: "btn btn-pink" %></li>
    <li><%= link_to "Write Review", new_restaurant_review_path(@restaurant.id), class: "btn btn-pink" %></li>
  </ul>
  <ul class="list-inline">
    <li><%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-pink" %></li>
    <li><%= link_to "Delete", restaurant_path(@restaurant), method: :delete, class: "btn btn-pink" %></li>
    <li><%= link_to "Home", restaurants_path, class: "btn btn-pink" %></li>
    </ul>
  </div>
</div>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<div class="container text-center restaurants">
  <% @reviews.each do |review| %>
  <div class="row card">
    <p><%= review.rating %></p>
    <p><%= review.content %></p>
  </div>
  <% end %>
  <div class="row card">
    <ul class="list-inline">
      <li><%= link_to "Home", restaurants_path, class: "btn btn-pink" %></li>
    </ul>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Write a New Review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, as: :select, collection: Review::RATING, include_blank: "Select a rating" %>
  <%= f.input :content %>
  <%= f.submit "Add a Review", class: "btn btn-pink" %>
<% end %>

app/views/reviews/show.html.erb
<div class="row card">
  <p><%= @review.rating %></p>
  <p><%= @review.content %></p>
</div>